safe:        false
auto:        false 
server:      false
server_port: 4000
baseurl:    /blog
url: http://localhost:4000

source:      .
destination: ../src/blog
plugins:     ./_plugins
exclude: newpost.rb

future:      false 
lsi:         false 
pygments:    true 
markdown:    maruku
permalink:  /:title 
