safe:        false
auto:        false 
server:      false
server_port: 4000
baseurl:    /mortgagebloom-blog/blog
url: http://localhost:4000

source:      .
destination: output
plugins:     ./_plugins
exclude: newpost.rb output

future:      false 
lsi:         false 
pygments:    true 
markdown:    maruku
permalink:  /:title 
